# Cloud Build config to build and push both training and inference images.
steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file=containers/training.Dockerfile
      - --tag=$_TRAINING_IMAGE
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file=containers/inference.Dockerfile
      - --tag=$_INFERENCE_IMAGE
      - .
images:
  - $_TRAINING_IMAGE
  - $_INFERENCE_IMAGE
substitutions:
  _TRAINING_IMAGE: europe-west3-docker.pkg.dev/propensity-to-subscr-eng-prod/pts-model/training:latest
  _INFERENCE_IMAGE: europe-west3-docker.pkg.dev/propensity-to-subscr-eng-prod/pts-model/inference:latest
