# Cloud Workflow: quarterly training job orchestration for Economedia PTS.
# Launches a Vertex AI Custom Job running the training container with
# explicit window parameters.

main:
  # 💡 FIX 1: Consolidate all parameters into a single map (e.g., 'input')
  params: [input]
  steps:
    - defaults:
        assign:
          - project: ${default(input.project_id, "propensity-to-subscr-eng-prod")}
          - location: ${default(input.region, "europe-west3")}
          - image: ${default(input.training_image, "europe-west3-docker.pkg.dev/propensity-to-subscr-eng-prod/pts-model/training:latest")}
          - machine: ${default(input.machine_type, "e2-standard-8")}
          - sa: ${default(input.service_account, "sa-ml-train@propensity-to-subscr-eng-prod.iam.gserviceaccount.com")}
        
          - run_id: sys.uuid()
          - now: sys.now()

          - resolved_freeze_0: ${default(input.freeze_date, time.format(sys.now() - 7*86400))} 
          - resolved_freeze: ${text.split(resolved_freeze_0, "T")[0]}
          - freeze_ts: ${resolved_freeze + "T00:00:00Z"}
          - resolved_start_0: ${time.format(time.parse(freeze_ts) - 180*86400)}
          - resolved_start: ${text.split(resolved_start_0, "T")[0]}
          - resolved_dne_start: ${default(input.dne_start, resolved_start)}
          - resolved_cap_start: ${default(input.cap_wall1_offer_start, resolved_start)}
          - base_args:
              - "--start_date"
              - ${resolved_start}
              - "--freeze_date"
              - ${resolved_freeze}
              - "--dne_start"
              - ${resolved_dne_start}
              - "--cap_wall1_offer_start"
              - ${resolved_cap_start}
          - job_args: ${list.concat(base_args, if(input.primary_label, ["--primary_label", input.primary_label], []))} 

    - launch_training:
        call: googleapis.aiplatform.v1.projects.locations.customJobs.create
        args:
          # region argument is required for the connector
          region: ${location}  
          parent: ${"projects/" + project + "/locations/" + location}
          body:
            displayName: ${"pts-training-" + text.substring(run_id, 0, 8)}
            jobSpec:
              serviceAccount: ${sa}
              workerPoolSpecs:
                - machineSpec:
                    machineType: ${machine}
                  replicaCount: 1
                  containerSpec:
                    imageUri: ${image}
                    args: ${job_args}
          connector_params:
            timeout: 216000
        result: training_job
    
    - wait_initial:
        call: sys.sleep
        args:
          seconds: 30
    
    - poll_status:
        call: googleapis.aiplatform.v1.projects.locations.customJobs.get
        args:
          name: ${training_job.name}
          region: ${location}  
        result: job_state
    
    - check_status:
        switch:
          - condition: ${job_state.state == "JOB_STATE_SUCCEEDED"}
            return:
              message: "Training completed"
              customJobName: ${training_job.name}
              runId: ${run_id}
          - condition: ${job_state.state in ["JOB_STATE_FAILED", "JOB_STATE_CANCELLED", "JOB_STATE_PAUSED"]}
            raise: ${"Training job ended with state " + job_state.state}
          - condition: ${true}
            next: wait_loop
            
    - wait_loop:
        call: sys.sleep
        args:
          seconds: 60
        next: poll_status